# File: config.conf
# Cấu hình biến môi trường toàn cục cho hệ thống Sing-box Manager

INSTALL_DIR="/usr/local/singbox-manager"
REPO_URL="https://raw.githubusercontent.com/Vietnamvpn/singbox-manager/main"
CONFIG_JSON="/usr/local/singbox-manager/config/config.json"
SINGBOX_BIN="/usr/local/bin/sing-box"
SERVICE_NAME="singbox.service"